### ISSUE TITLE
Add Backend dev setup documentation

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-trip-planner-backend#12]
Document what's needed for developing the backend project (README)

Acceptance criteria:

Please documents
- Prerequisites: minimal version of JDK, maven, mysql etc. what needs to be installed in order to work on the project
- Which tools are used
- How test, build, run project locally? including command (e.v. ./mvnw clean test), environment variables
- How to deploy project (tools, commands etc)

**Comment by Thebloodraccoon** [comment]
@ownerofglory can you explain in more detail what exactly needs to be added?

**Comment by ownerofglory** [comment]
@Thebloodraccoon sure. Imagine yourself in a role of a new developer that's just joined the team and is about to start working on this project. What do you need to start?
