### ISSUE TITLE
Add and configure Surefire and JaCoCo plugins

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-trip-planner-backend#32]
- Add the lates stable version of maven surefire plugin
- Add JaCoCo plugin
- Configure JaCoCo to generate a report during mvn package phase

**Comment by Thebloodraccoon** [comment]
Do I need to move plugin versions to properties?

**Comment by ownerofglory** [comment]
@Thebloodraccoon yes, please move them to props
