### ISSUE TITLE
[EXPLO] Investigate places API

### ISSUE THREAD

**Issue by ownerofglory** [ownerofglory/hillel-trip-planner-backend#5]
App requires the data about places (hotels, restaurants, museums, sightseeings).
Look for 3rd party API that could provide this data. 
Compare most suitable vendors. Consider pricing model (free, limited free, payed, etc), authentication (none, API key, OAuth, etc)
Document results

Acceptance criteria:
- comparison document created 

Examples:
- [OpenTripMap](https://dev.opentripmap.org/product)
- [Yelp for devs](https://www.yelp.com/developers)
- [WikiMapia](http://wikimapia.org/api?action=how_to)
- [Trip Advisor](https://developer-tripadvisor.com/content-api/)
- [Four Square for dev](https://location.foursquare.com/developer/)

**Comment by ownerofglory** [comment]
other example https://www.geoapify.com/places-api

**Comment by Bugusers** [comment]
@ownerofglory check this https://github.com/ownerofglory/hillel-trip-planner-backend/wiki/Investigate-places-API
